on:
  workflow_call:
    inputs:
      REGISTRY:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      VERSION:
        required: true
        type: string
      SKIP_RELEASE:
        required: true
        type: string
        description: "Set to 'true' will disable publishing/releasing of artefact!"
      BRANCH_TO_PUSH:
        required: true
        type: string
        default: "refs/heads/main"

jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Log in to the Container Registry
        uses: docker/login-action@v3
        if: ${{ github.ref == inputs.BRANCH_TO_PUSH && needs.dryrun.outputs.skipRelease == 'false' }}
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.IMAGE_NAME }}
          tags: ${{ inputs.VERSION }}

      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: ${{ github.ref == inputs.BRANCH_TO_PUSH && needs.dryrun.outputs.skipRelease == 'false' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ inputs.VERSION }}
            BUILD_TIMESTAMP=${{ github.event.repository.created_at }}
            COMMIT_HASH=${{ github.sha }}
            APP_NAME=${{ github.event.repository.name }}
            REPOSITORY=${{ github.repository }}
            REPOSITORY_URL=${{ github.repositoryUrl }}
            WORKFLOW_LINK=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}


