name: Commit-Linting

on:
  workflow_call:
  pull_request:

permissions:
  contents: read # for checkout

jobs:
  commitlint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: markuslackner/semantic-release-installer-action@main
      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: |
          echo "## 💡PR Commit Linting" >> $GITHUB_STEP_SUMMARY
          echo "check logs for details..." >> $GITHUB_STEP_SUMMARY
          
          npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose
